server:
  port: 8083
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 3118659412@qq.com
    password: iecshggikvevdfic
  datasource:
    username: root
    password: bzp510719
    url: jdbc:mysql://47.115.230.231:3306/spider_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml
