server:
  port: 8083

spring:
  profiles:
    active: dev
  ## 邮件
  mail:
    ## 协议
    protocol: smtp
    ## 地址
    host: smtp.qq.com
    ## 端口
    port: 587
    ## 账户
    username: 3118659412@qq.com
    ## 密钥
    password: iecshggikvevdfic
    ## 字符集
    default-encoding: UTF-8
    ## 测试
    test-connection: false
    ## 来源
    from: 854085467@qq.com

mybatis-plus:
  type-aliases-package: com.example.demo.modules.spider.entity
  mapper-locations: classpath*:com/example/demo/modules/**/xml/**.xml
