server:
  port: 8083

spring:
  profiles:
    active: pro

mybatis-plus:
  type-aliases-package: com.example.demo.modules.spider.entity
  mapper-locations: classpath*:com/example/demo/modules/**/xml/**.xml
