spring:
  datasource:
    username: root
    password: ENC(kFKXwL1fSjzobAOFyJIGx/1Yu5E+aW8y1HNIo6fKHUfjvm8oga8yiOwAT8abOdND)
    url: jdbc:mysql://localhost:3306/spider_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
